
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_db
    username: root
    password: khanghy123
    hikari:
      maximum-pool-size: 15
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate.format-sql: true
      hibernate.jdbc.batch_size: 2000
      hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
      hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext


